### ISSUE TITLE
Subsequent arrival times on route. 

### ISSUE THREAD

**Issue by AzNBagel** [SomethingExplosiveApps/Development#10]
If I tap on the max or bus I plan on taking. It would be nice to see the estimated arrival times for that vehicle at its subsequent stops. Allowing me to see which max or bus I need to take to make it to a destination.

**Comment by something15525** [comment]
Closing this issue since it would be considered a new feature, and I am mostly planning on stopping new development on this application.

**Comment by AzNBagel** [comment]
Disappointed

**Comment by something15525** [comment]
¯\\_(ツ)_/¯
